"""Add business directory tables

Revision ID: 7dad4fa62aae
Revises: bbaad4dfba62
Create Date: 2025-09-17 17:00:16.220132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dad4fa62aae'
down_revision = 'bbaad4dfba62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_settings_key_public', 'system_settings', ['key', 'is_public'], unique=False)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_users_google_id', 'users', ['google_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('hours', sa.JSON(), nullable=True),
    sa.Column('price_range', sa.String(length=10), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_businesses_approved_active', 'businesses', ['is_approved', 'is_active'], unique=False)
    op.create_index('idx_businesses_category_city', 'businesses', ['category', 'city'], unique=False)
    op.create_index('idx_businesses_featured', 'businesses', ['is_featured', 'is_approved', 'is_active'], unique=False)
    op.create_index('idx_businesses_owner_approved', 'businesses', ['owner_id', 'is_approved'], unique=False)
    op.create_index('idx_businesses_state_city', 'businesses', ['state', 'city'], unique=False)
    op.create_index(op.f('ix_businesses_category'), 'businesses', ['category'], unique=False)
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=True)
    op.create_index(op.f('ix_businesses_state'), 'businesses', ['state'], unique=False)
    op.create_table('business_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('phone_calls', sa.Integer(), nullable=True),
    sa.Column('website_visits', sa.Integer(), nullable=True),
    sa.Column('direction_requests', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_business_date', 'business_analytics', ['business_id', 'date'], unique=False)
    op.create_index(op.f('ix_business_analytics_date'), 'business_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_business_analytics_id'), 'business_analytics', ['id'], unique=False)
    op.create_table('business_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('claim_reason', sa.Text(), nullable=True),
    sa.Column('supporting_documents', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_claims_business_status', 'business_claims', ['business_id', 'status'], unique=False)
    op.create_index('idx_claims_user_status', 'business_claims', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_business_claims_id'), 'business_claims', ['id'], unique=False)
    op.create_table('business_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=100), nullable=True),
    sa.Column('reviewer_email', sa.String(length=255), nullable=True),
    sa.Column('reviewer_phone', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reviews_business_approved', 'business_reviews', ['business_id', 'is_approved'], unique=False)
    op.create_index('idx_reviews_business_rating', 'business_reviews', ['business_id', 'rating'], unique=False)
    op.create_index(op.f('ix_business_reviews_id'), 'business_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_reviews_id'), table_name='business_reviews')
    op.drop_index('idx_reviews_business_rating', table_name='business_reviews')
    op.drop_index('idx_reviews_business_approved', table_name='business_reviews')
    op.drop_table('business_reviews')
    op.drop_index(op.f('ix_business_claims_id'), table_name='business_claims')
    op.drop_index('idx_claims_user_status', table_name='business_claims')
    op.drop_index('idx_claims_business_status', table_name='business_claims')
    op.drop_table('business_claims')
    op.drop_index(op.f('ix_business_analytics_id'), table_name='business_analytics')
    op.drop_index(op.f('ix_business_analytics_date'), table_name='business_analytics')
    op.drop_index('idx_analytics_business_date', table_name='business_analytics')
    op.drop_table('business_analytics')
    op.drop_index(op.f('ix_businesses_state'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_category'), table_name='businesses')
    op.drop_index('idx_businesses_state_city', table_name='businesses')
    op.drop_index('idx_businesses_owner_approved', table_name='businesses')
    op.drop_index('idx_businesses_featured', table_name='businesses')
    op.drop_index('idx_businesses_category_city', table_name='businesses')
    op.drop_index('idx_businesses_approved_active', table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_google_id', table_name='users')
    op.drop_index('idx_users_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index('idx_settings_key_public', table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
