"""Initial migration - create all tables

Revision ID: bbaad4dfba62
Revises: 
Create Date: 2025-09-11 16:15:13.207412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbaad4dfba62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('articles_found', sa.Integer(), nullable=True),
    sa.Column('articles_processed', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_logs_created_at'), 'api_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_logs_id'), 'api_logs', ['id'], unique=False)
    op.create_table('incident_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('severity_level', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_incident_categories_id'), 'incident_categories', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('state_name', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_major_city', sa.Boolean(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_city'), 'locations', ['city'], unique=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_state_code'), 'locations', ['state_code'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_table('system_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_incidents', sa.Integer(), nullable=True),
    sa.Column('incidents_by_state', sa.Text(), nullable=True),
    sa.Column('incidents_by_type', sa.Text(), nullable=True),
    sa.Column('incidents_by_severity', sa.Text(), nullable=True),
    sa.Column('api_calls_made', sa.Integer(), nullable=True),
    sa.Column('api_errors', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_stats_date'), 'system_stats', ['date'], unique=False)
    op.create_index(op.f('ix_system_stats_id'), 'system_stats', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('location_text', sa.String(length=200), nullable=True),
    sa.Column('crime_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incidents_severity_time', 'incidents', ['severity', 'published_at'], unique=False)
    op.create_index('idx_incidents_state_time', 'incidents', ['state', 'published_at'], unique=False)
    op.create_index('idx_incidents_type_time', 'incidents', ['crime_type', 'published_at'], unique=False)
    op.create_index(op.f('ix_incidents_city'), 'incidents', ['city'], unique=False)
    op.create_index(op.f('ix_incidents_crime_type'), 'incidents', ['crime_type'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_published_at'), 'incidents', ['published_at'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_state'), 'incidents', ['state'], unique=False)
    op.create_index(op.f('ix_incidents_title'), 'incidents', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_title'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_state'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_published_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_crime_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_city'), table_name='incidents')
    op.drop_index('idx_incidents_type_time', table_name='incidents')
    op.drop_index('idx_incidents_state_time', table_name='incidents')
    op.drop_index('idx_incidents_severity_time', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_system_stats_id'), table_name='system_stats')
    op.drop_index(op.f('ix_system_stats_date'), table_name='system_stats')
    op.drop_table('system_stats')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_locations_state_code'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_city'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_incident_categories_id'), table_name='incident_categories')
    op.drop_table('incident_categories')
    op.drop_index(op.f('ix_api_logs_id'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_created_at'), table_name='api_logs')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
